[package]
name = "tnetstr-serde"
version = "0.1.0"
authors = ["Tom <anemail@somemail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive ="1.0"
tnetstr = { path = "../tnetstr", version = "0.1" }